title: "adanac's blog"
baseurl: /week
url: "https://adanac.github.io/week/"
markdown: redcarpet
redcarpet:
   extensions: ["hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

permalink: pretty
highlighter: pygments
paginate: 3
